server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: currency-rate-tracker-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/currency_rate_tracker}
    username: ${DB_USERNAME:currency_rate_tracker}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

integracao:
  awesome-api:
    base-url: ${AWESOME_API_BASE_URL:https://economia.awesomeapi.com.br}
    connect-timeout-millis: ${AWESOME_API_CONNECT_TIMEOUT_MILLIS:3000}
    read-timeout-millis: ${AWESOME_API_READ_TIMEOUT_MILLIS:3000}

cotacao:
  atualizacao:
    intervalo-millis: ${COTACAO_ATUALIZACAO_INTERVALO_MILLIS:60000}
